language: node_js
node_js:
- "stable"
deploy:
provider: pages
skip_cleanup: true
github_token: $https://app.travis-ci.com/ryanhihi/comp3104.svg?token=U3Ukq6H8sps2qioMEcVx
local_dir: build
on:
branch: master